apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  labels:
    app: jenkins
spec:
  containers:
  - name: jenkins
    image: jenkins/jenkins:lts
    ports:
    - name: jenkins-port
      containerPort: 8080
    volumeMounts:
    - mountPath: /jenkins
      name: jenkins-volume
  volumes:
  - name: jenkins-volume
    emptyDir: {}
